-- CREATE TABLE SERVICE (
--     SERVICO serial PRIMARY KEY,
--     VALOR VARCHAR(50),
--     DESCRICAO INTEGER
-- );

-- INSERT INTO SERVICE (SERVICO, VALOR, DESCRICAO) VALUES(1, '', 150);
-- INSERT INTO SERVICE (SERVICO, VALOR, DESCRICAO) VALUES(2, '', 154);

select * from SERVICE